obj-$(CONFIG_MXC_MLB) += mlb/
obj-$(CONFIG_MXC_SIM) += sim/
obj-$(CONFIG_MXC_VPU) += vpu/
obj-$(CONFIG_MXC_IPU_V3) += ipu3/
obj-$(CONFIG_MXC_HDMI_CEC) += hdmi-cec/
obj-$(CONFIG_MXC_GPU_VIV_5_0_11_P86) += gpu-viv/
obj-$(CONFIG_MXC_GPU_VIV_5_0_11_P74) += gpu-viv_5.0.11.p7.4/
obj-$(CONFIG_MXC_MIPI_CSI2) += mipi/
